# Generated by Django 5.1.4 on 2025-01-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inventoryitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
