name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run pipeline when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Run pipeline for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: python manage.py migrate
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

      - name: Run tests
        run: python manage.py test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
